#operator matematika
print(True)
print(False)
print('Addition: 1 + 2')
print('Addition:', 1 + 2)
print('Subtraction:', 2 - 2)
print('Multiplication:', 2 * 4)
print('Division:', 4 / 2)
print('Division without the remainder:', 4 // 2)
print('Modulus:', 5 % 7)
print('Exponentiation:', 2 ** 4)

#operator komparasi
print(3 > 2)
print(3 >= 2)
print(3 < 2)
print(2 < 3)
print(2 <= 3)
print(3 == 2)
print(3 != 2)
print(len('mango') == len('avocado'))
print(len('mango') != len('avocado'))
print(len('mango') < len('avocado'))
print(len('milk') != len('meat'))
print(len('milk') == len('meat'))
print(len('tomato') == len('potato'))
print(len('python') > len('dragon'))

print('1 is 1', 1 is 1)
print('1 is not 2', 1 is not 2)
print('A in Asabeneh', 'A' in 'Asabeneh')
print('B in Asabeneh', 'B' in 'Asabeneh')
print('coding' in 'coding for all')
print('a in an', 'a' in 'an')
print('4 is 2 ** 2', 4 is 2 ** 2)

#operator logika
print(3 > 2 and 4 > 3)
print(3 > 2 and 4 < 3)
print(3 < 2 and 4 < 3)
print('True and True ', True and True)
print(3 > 2 or 4 > 3)
print(3 > 2 or 4 < 3)
print(3 < 2 or 4 < 3)
print('True or False: ', True or False)
print( not 3 > 2)
print(not True)
print(not False)
print(not not True)
print(not not False)

