print(True)
print(False)
print('Addition: 1 + 2')
print('Addition:', 1 + 2)
print('Subtraction:', 2 - 2)
print('Multiplication:', 2 * 4)
print('Division:', 4 / 2)
print('Division without the remainder:', 4 // 2)
print('Modulus:', 5 % 7)
print('Exponentiation:', 2 ** 4)